### ISSUE TITLE
Question: Autostart-Scripts not used (dwm)

### ISSUE THREAD

**Issue by Ba-So** [phenax/nixos-dotfiles#1]
Hey Phenax, 

First: Thanks for sharing your configuration, this has helped me a ton to transition from arch to nixos!

I can't seem to get dwmblocks to run at startup, and have traced it down to my autostart.sh not being executed.

How is the `packages/dwm/autostart.sh` triggered? I don't understand when it is moved/executed in this configuration.

**Comment by phenax** [comment]
Hey! That part is a bit of mess that I quickly hacked around to make it work. The `autostart.sh` is called from inside my dwm fork [here](https://github.com/phenax/dwm/blob/0efa5d1c5e9ea7d3db58a6c761ceca5abd974642/config.def.h#L171). But it should be fine to call it from your xinit as well. Hope that helps.

Mostly due to lazyness, I call the script directly from my config but I'd suggest tracking it via nixos by moving it to the `.config` directory using `home.files` in home manager or moving it to `/etc` using `environment.etc`.

**Comment by Ba-So** [comment]
Thanks for your reply! Yes I figured that I should probably do it through my xprofile/xinitrc.

After some tinkering around your proposed "proper" solution works just fine. Thanks a bunch for your help!
